name: Update Invidious Instances

on:
  schedule:
    # Runs every 3 hours
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run the script
      run: |
        python check_invidious_instances.py

    - name: Commit and push changes
      run: |
        git add output/
        git commit -m "Update Invidious instances output" || echo "No changes to commit"
        git push
      # Ignore errors for cases where there are no changes to commit
      continue-on-error: true
